name: bump
description: A sample command-line application.
version: 1.0.0+1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  args: ^2.6.0
  cli_spin: ^1.0.1
  process_run: ^1.2.2
  yaml: ^3.1.2
  yaml_edit: ^2.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
